name: unit test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux.4xlarge.nvidia.gpu]
        python-version: [3.7]
        cuda-tag: ["cu11"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install CUDA 11.3
        shell: bash -l {0}
        run: |
          # sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          sudo rpm --install --force https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          sudo yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
          sudo yum clean expire-cache
          sudo yum install -y nvidia-driver-latest-dkms
          sudo yum install -y nvidia-cuda-toolkit
          sudo yum install -y nvidia-utils
          sudo yum install -y cuda-11-3
          sudo yum install -y cuda-drivers
          sudo yum install -y libcudnn8-devel
      - name: setup Path
        run: |
          echo /usr/local/cuda-11.3/bin >> $GITHUB_PATH
          echo /usr/local/bin >> $GITHUB_PATH
      - name: nvcc check
        run: |
          nvcc --version
          nvidia-smi
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          set -eux
          conda activate test
          pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
          python -c "import torch; print(torch.cuda.is_available())"
      #     pip install -r requirements.txt
      #     pip install -r dev-requirements.txt
      #     pip install -e ".[dev]"
      # - name: Run unit tests with coverage
      #   shell: bash -l {0}
      #   run: |
      #     set -eux
      #     conda activate test
      #     pytest --cov=. --cov-report xml tests -vv
      # - name: Upload Coverage to Codecov
      #   uses: codecov/codecov-action@v2
